/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Windows;

import DAO.CategoriaDAO;
import DAO.CorredorDAO;
import VO.CategoriaVO;
import VO.CorredorVO;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class modificarCorredor extends javax.swing.JFrame {

    private int x;
    private int y;
    public String dnicorredor;
    
    public modificarCorredor(String dnicor) {
        initComponents();
        setLocationRelativeTo(null);
        dnicorredor = dnicor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        txtNombreCor = new javax.swing.JTextField();
        txtApellidoCor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDNiCor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEdadDCor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroCor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxSexCor = new javax.swing.JComboBox<>();
        btnModifCor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setMinimumSize(new java.awt.Dimension(380, 300));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-property-323.png"))); // NOI18N
        jLabel1.setText("Registro Modificar Corredor");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);

        labelExit.setBackground(new java.awt.Color(102, 102, 102));
        labelExit.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        labelExit.setForeground(new java.awt.Color(255, 255, 255));
        labelExit.setText(" X");
        labelExit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtNombreCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCorActionPerformed(evt);
            }
        });

        txtApellidoCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel3.setText("Nombre");

        txtDNiCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNiCorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel10.setText("DNI");

        txtEdadDCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadDCorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel6.setText("Edad ");

        txtNumeroCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel5.setText("Numero");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel4.setText("Sexo");

        comboBoxSexCor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        comboBoxSexCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        btnModifCor.setBackground(new java.awt.Color(51, 0, 255));
        btnModifCor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnModifCor.setForeground(new java.awt.Color(255, 255, 255));
        btnModifCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plusWhite-15.png"))); // NOI18N
        btnModifCor.setText("Modificar");
        btnModifCor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnModifCor.setBorderPainted(false);
        btnModifCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifCorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel9.setText("Apellido");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtEdadDCor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNumeroCor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtDNiCor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(comboBoxSexCor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnModifCor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(txtDNiCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadDCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSexCor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifCor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_labelExitMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1
        //System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
        setLocation(ubicacion.x - x, ubicacion.y - y);//3
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnModifCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifCorActionPerformed
        CategoriaVO catvo = new CategoriaVO();
        CategoriaDAO catdao = new CategoriaDAO();
        CorredorVO corvo = new CorredorVO();
        CorredorDAO cordao = new CorredorDAO();
        //Agrego otro dao y vo para que pueda obtener los indices de los datos del jtable antes de que sea modificado
        CorredorVO catvoIndice = new CorredorVO();
        
        
        int j = 0;
        String nombre = txtNombreCor.getText();
        String apellido = txtApellidoCor.getText();
        String DNI = String.valueOf(txtDNiCor.getText());
        int edad = Integer.parseInt(txtEdadDCor.getText());
        String numero = String.valueOf(txtNumeroCor.getText());
        String sexo = comboBoxSexCor.getSelectedItem().toString();
        int categoria = -1;
        
        ArrayList<CategoriaVO> list = catdao.Listar_CategoriaVO();
        if (list.size() > 0) {
            for(int i=0; i<list.size(); i++){
            catvo = list.get(i);
                if (edad >= catvo.getDesdeAnio() && edad <= catvo.getHastaAnio()) {
                categoria = catvo.getId_categoria();
                }
            }
        }


        try {
            if (validaciones.isString(nombre)) {
                corvo.setNombre(nombre);
                if (validaciones.isString(apellido)) {
                    corvo.setApellido(apellido);
                    if (validaciones.isNumber(DNI)) {
                        corvo.setDNI(Integer.parseInt(DNI));
                        if (validaciones.isNumber(String.valueOf(edad))) {
                            corvo.setEdad(edad);
                            if (validaciones.isNumber(numero)) {
                                corvo.setNumero(Integer.parseInt(numero));
                                corvo.setSexoCorredor(sexo);
                                corvo.setId_categoria(categoria);
                                corvo.setTiempo("00:00:00");
                                catvoIndice.setDNI(Integer.parseInt(dnicorredor));

                                j = cordao.Modificar_CorredorVO(corvo, catvoIndice.getDNI());
                                if (j == 1) {
                                    JOptionPane.showMessageDialog(this, "Datos Agregados Correctamente");
                                    txtNombreCor.setText("");
                                    txtApellidoCor.setText("");
                                    txtDNiCor.setText("");
                                    txtEdadDCor.setText("");
                                    txtNumeroCor.setText("");
                                } else {
                                    JOptionPane.showMessageDialog(this, "Error al Agregar los Datos");
                                }
                            }else {
                                    JOptionPane.showMessageDialog(this, "Ingrese correctamente el numero");
                                    txtNumeroCor.setText("");
                            }
                        }else {
                                JOptionPane.showMessageDialog(this, "Ingrese correctamente la edad");
                                txtEdadDCor.setText("");
                        }
                    }else {
                            JOptionPane.showMessageDialog(this, "Ingrese correctamente el DNI");
                            txtDNiCor.setText("");
                    }
                }else {
                        JOptionPane.showMessageDialog(this, "Ingrese correctamente el DNI");
                        txtApellidoCor.setText("");
                }
            }else {
                    JOptionPane.showMessageDialog(this, "Ingrese correctamente el DNI");
                    txtNombreCor.setText("");
            }

            //            catvo.setSexocategoria(comboSexoModC.getSelectedItem().toString());
            //            catvoIndice.setSexocategoria(sexoModCat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModifCorActionPerformed

    private void txtNombreCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCorActionPerformed

    private void txtApellidoCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCorActionPerformed

    private void txtDNiCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNiCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNiCorActionPerformed

    private void txtEdadDCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadDCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadDCorActionPerformed

    private void txtNumeroCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String mod = "";
                new modificarCorredor(mod).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnModifCor;
    private javax.swing.JComboBox<String> comboBoxSexCor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelExit;
    private javax.swing.JTextField txtApellidoCor;
    private javax.swing.JTextField txtDNiCor;
    private javax.swing.JTextField txtEdadDCor;
    private javax.swing.JTextField txtNombreCor;
    private javax.swing.JTextField txtNumeroCor;
    // End of variables declaration//GEN-END:variables

}
